/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AbstractENS"): TruffleContracts.AbstractENSContract;
      require(name: "ACL"): TruffleContracts.ACLContract;
      require(name: "APMRegistry"): TruffleContracts.APMRegistryContract;
      require(name: "AppProxyBase"): TruffleContracts.AppProxyBaseContract;
      require(
        name: "AppProxyFactory"
      ): TruffleContracts.AppProxyFactoryContract;
      require(name: "AppProxyPinned"): TruffleContracts.AppProxyPinnedContract;
      require(
        name: "AppProxyUpgradeable"
      ): TruffleContracts.AppProxyUpgradeableContract;
      require(name: "AppStorage"): TruffleContracts.AppStorageContract;
      require(name: "AragonApp"): TruffleContracts.AragonAppContract;
      require(name: "Autopetrified"): TruffleContracts.AutopetrifiedContract;
      require(
        name: "BaseEVMScriptExecutor"
      ): TruffleContracts.BaseEVMScriptExecutorContract;
      require(name: "CallsScript"): TruffleContracts.CallsScriptContract;
      require(name: "DAOFactory"): TruffleContracts.DAOFactoryContract;
      require(name: "DelegateProxy"): TruffleContracts.DelegateProxyContract;
      require(
        name: "DepositableDelegateProxy"
      ): TruffleContracts.DepositableDelegateProxyContract;
      require(
        name: "DepositableStorage"
      ): TruffleContracts.DepositableStorageContract;
      require(
        name: "ENSSubdomainRegistrar"
      ): TruffleContracts.ENSSubdomainRegistrarContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERCProxy"): TruffleContracts.ERCProxyContract;
      require(
        name: "EVMScriptRegistry"
      ): TruffleContracts.EVMScriptRegistryContract;
      require(
        name: "EVMScriptRegistryFactory"
      ): TruffleContracts.EVMScriptRegistryFactoryContract;
      require(
        name: "EVMScriptRunner"
      ): TruffleContracts.EVMScriptRunnerContract;
      require(name: "IACL"): TruffleContracts.IACLContract;
      require(name: "IACLOracle"): TruffleContracts.IACLOracleContract;
      require(
        name: "IEVMScriptExecutor"
      ): TruffleContracts.IEVMScriptExecutorContract;
      require(
        name: "IEVMScriptRegistry"
      ): TruffleContracts.IEVMScriptRegistryContract;
      require(name: "IKernel"): TruffleContracts.IKernelContract;
      require(name: "Initializable"): TruffleContracts.InitializableContract;
      require(
        name: "IVaultRecoverable"
      ): TruffleContracts.IVaultRecoverableContract;
      require(name: "Kernel"): TruffleContracts.KernelContract;
      require(name: "KernelProxy"): TruffleContracts.KernelProxyContract;
      require(name: "KernelStorage"): TruffleContracts.KernelStorageContract;
      require(name: "Petrifiable"): TruffleContracts.PetrifiableContract;
      require(name: "PublicResolver"): TruffleContracts.PublicResolverContract;
      require(name: "Repo"): TruffleContracts.RepoContract;
      require(
        name: "VaultRecoverable"
      ): TruffleContracts.VaultRecoverableContract;
    }
  }
}
