name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 11
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: npm run git:clean
      - run: npm run publish:nightly
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
